# Generated by Django 4.2.4 on 2023-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coregame", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamescoring",
            name="board_size",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="gamescoring",
            name="timing",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
