# Generated by Django 4.2.4 on 2023-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coregame", "0002_gamescoring_board_size_gamescoring_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamescoring",
            name="board_size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
